
server:
  servlet:
    context-path: /academia/api

spring:
  datasource:
    url: jdbc:h2:mem:demodb
    username: sa
    password:
    driverClassName: org.h2.Driver

  h2:
    console:
      enable: true
      path: /h2-console